package unibz.winter.model;

/**
 * Created by jetzt on 12/10/15.
 */
public class ModelUser {

    private String ID;
    private String username;


    // RELATIONAL: ID COULD BE GENERATED BY THE DATABASE , INCREMENTAL : 1,2,3,4,5.....
    // NON-RELATIONAL:  GENERATE THE ID.
    public ModelUser(String username)
    {
        this.username  = username;
    }

    public String getUsername() {

        return this.username;
    }

    public String getID() {

        return this.ID;
    }

    public void setUsername(String username){
        this.username = username ;
    }


}
